# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)
b <- board_folder(path = ".")
v <- vetiver_pin_read(b, "telco")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v, type = "prob")
}
